src/objects/Vacation_Request__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Vacation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestType__c</fullName>
        <label>RequestType</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vacation</fullName>
                </value>
                <value>
                    <fullName>Sick</fullName>
                </value>
                <value>
                    <fullName>Unpaid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkingDays__c</fullName>
        <label>WorkingDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vacation Request</label>
    <nameField>
        <displayFormat>R-{0}</displayFormat>
        <label>Vacation Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VacationRequestsController.cls
public class VacationRequestsController {

	// Get all vacation requests in an ascending order
	@AuraEnabled(cacheable=true)
	public static List<Vacation_Request__c> getVacationRequestList(Boolean isOnlyMy) {
		if (!isOnlyMy) {
			return [
					SELECT Name, RequestType__c, StartDate__c, EndDate__c, WorkingDays__c, Manager__c, Status__c
					FROM Vacation_Request__c
					WITH SECURITY_ENFORCED
					ORDER BY Name ASC
			];
		} else {
			String currentId = UserInfo.getUserId();

			return [
					SELECT Name, RequestType__c, StartDate__c, EndDate__c, WorkingDays__c, Manager__c, Status__c
					FROM Vacation_Request__c
					WHERE Manager__c = :currentId
					WITH SECURITY_ENFORCED
					ORDER BY Name ASC
			];
		}
	}

	// Get user name by Id
	@AuraEnabled(cacheable=true)
	public static List<User> getUserName(String userId) {
		return [
				SELECT Name
				FROM User
				WHERE Id = :userId
				WITH SECURITY_ENFORCED
		];
	}

	// Submit vacation request with id requestId
	@AuraEnabled
	public static Boolean submitVacationRequest(String requestId) {
		List<Vacation_Request__c> vacationRequestList = [
				SELECT Name, Status__c
				FROM Vacation_Request__c
				WHERE Name = :requestId
				WITH SECURITY_ENFORCED
		];

		if (vacationRequestList.isEmpty()) {
			// No records found, throw an error
			return false;
		}

		// Changing status
		vacationRequestList[0].Status__c = 'Submitted';
		// Updating row
		update vacationRequestList;

		return true;
	}

	// Approve vacation request with id requestId
	@AuraEnabled
	public static Boolean approveVacationRequest(String requestId) {
		List<Vacation_Request__c> vacationRequestList = [
				SELECT Name, Status__c
				FROM Vacation_Request__c
				WHERE Name = :requestId
				WITH SECURITY_ENFORCED
		];

		if (vacationRequestList.isEmpty()) {
			// No records found, throw an error
			return false;
		}

		// Changing status
		vacationRequestList[0].Status__c = 'Approved';
		// Updating row
		update vacationRequestList;

		return true;
	}

	// Remove vacation request with id requestId
	@AuraEnabled
	public static Boolean removeVacationRequest(String requestId) {
		List<Vacation_Request__c> vacationRequestList = [
				SELECT Name, Status__c
				FROM Vacation_Request__c
				WHERE Name = :requestId
				WITH SECURITY_ENFORCED
		];

		if (vacationRequestList.isEmpty()) {
			// No records found, throw an error
			return false;
		}

		// Try to delete record
		try {
			delete vacationRequestList[0];
		} catch (DmlException e) {
			// Exception thrown, it's reasonable to just return false
			return false;
		}
		return true;
	}

}