src/objects/Vacation_Request__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Vacation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestType__c</fullName>
        <label>RequestType</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vacation</fullName>
                </value>
                <value>
                    <fullName>Sick</fullName>
                </value>
                <value>
                    <fullName>Unpaid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkingDays__c</fullName>
        <label>WorkingDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vacation Request</label>
    <nameField>
        <displayFormat>R-{0}</displayFormat>
        <label>Vacation Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VacationRequestsControllerTests.cls
@IsTest
public class VacationRequestsControllerTests {

	@IsTest static void testGetRequestsWithoutFilter() {
		List<VacationRequestsController.Request> requests = VacationRequestsController.getVacationRequestList(false);
		List<Vacation_Request__c> valid = [
				SELECT Name, RequestType__c, StartDate__c, EndDate__c, WorkingDays__c, Owner.Name, Manager__c, Manager__r.Name, Status__c
				FROM Vacation_Request__c
		];

		System.assertEquals(valid.size(), requests.size());
	}

	@IsTest static void testGetRequestsWithFilter() {
		String currentId = UserInfo.getUserId();
		List<VacationRequestsController.Request> requests = VacationRequestsController.getVacationRequestList(true);
		List<Vacation_Request__c> valid = [
				SELECT Name, RequestType__c, StartDate__c, EndDate__c, WorkingDays__c, Owner.Name, Manager__c, Manager__r.Name, Status__c
				FROM Vacation_Request__c
				WHERE Manager__c = :currentId
		];

		System.assertEquals(valid.size(), requests.size());
	}

	@IsTest static void getCurrentUserManager() {
		String currentId = UserInfo.getUserId();
		User userManager = VacationRequestsController.getUserManager(currentId);
		User valid = [
				SELECT ManagerId
				FROM User
				WHERE Id = :currentId
				WITH SECURITY_ENFORCED
				LIMIT 1
		];

		System.assertEquals(valid.ManagerId, userManager.ManagerId);
	}

}